name: Publish Package

on:
  push:
    branches:
      - main  # Triggers when changes are pushed to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Skip this if you don't have tests

      - name: Publish to GitHub Packages
        run: npm run prepublishOnly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: npm run publish:public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JP_TOKEN_SCOPED }}


